<a href="https://colab.research.google.com/github/khushikayy/sklearn_library/blob/main/Sklearn(1_2)_Feature_Scaling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Scikit-learn Builtin Datasets

In [ ]:
from sklearn import datasets

In [ ]:
breast = datasets.load_breast_cancer()

In [ ]:
breast.data

array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]])

In [ ]:
X,y = datasets.load_iris(return_X_y=True)
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

## Test-Train Split

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('/content/CAR DETAILS FROM CAR DEKHO.csv')

In [ ]:
df.head()

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner
0,Maruti 800 AC,2007,60000,70000,Petrol,Individual,Manual,First Owner
1,Maruti Wagon R LXI Minor,2007,135000,50000,Petrol,Individual,Manual,First Owner
2,Hyundai Verna 1.6 SX,2012,600000,100000,Diesel,Individual,Manual,First Owner
3,Datsun RediGO T Option,2017,250000,46000,Petrol,Individual,Manual,First Owner
4,Honda Amaze VX i-DTEC,2014,450000,141000,Diesel,Individual,Manual,Second Owner

In [ ]:
X = df.drop('selling_price', axis = 1)
y = df['selling_price']
# Alternate way is to use iloc

In [ ]:
X.shape

(4340, 7)

In [ ]:
y.shape

(4340,)

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [ ]:
X_train.shape

(3472, 7)

In [ ]:
X_test.shape

(868, 7)

In [ ]:
y_train.shape

(3472,)

In [ ]:
y_test.shape

(868,)

In [ ]:
df = df[['selling_price','km_driven','year']]
df

      selling_price  km_driven  year
0             60000      70000  2007
1            135000      50000  2007
2            600000     100000  2012
3            250000      46000  2017
4            450000     141000  2014
...             ...        ...   ...
4335         409999      80000  2014
4336         409999      80000  2014
4337         110000      83000  2009
4338         865000      90000  2016
4339         225000      40000  2016

[4340 rows x 3 columns]

## Applying Normalisation: MinMax Scaling

In [ ]:
from sklearn.preprocessing import MinMaxScaler

In [ ]:
scaler = MinMaxScaler()

In [ ]:
scale_df = scaler.fit_transform(df)

In [ ]:
scale_df

array([[0.0045045 , 0.08678301, 0.53571429],
       [0.01295045, 0.06198751, 0.53571429],
       [0.06531532, 0.12397626, 0.71428571],
       ...,
       [0.01013514, 0.10290008, 0.60714286],
       [0.09515766, 0.11157851, 0.85714286],
       [0.02308559, 0.04958976, 0.85714286]])

In [ ]:
scale_df = pd.DataFrame(scale_df,columns=df.columns)
scale_df

      selling_price  km_driven      year
0          0.004505   0.086783  0.535714
1          0.012950   0.061988  0.535714
2          0.065315   0.123976  0.714286
3          0.025901   0.057028  0.892857
4          0.048423   0.174807  0.785714
...             ...        ...       ...
4335       0.043919   0.099181  0.785714
4336       0.043919   0.099181  0.785714
4337       0.010135   0.102900  0.607143
4338       0.095158   0.111579  0.857143
4339       0.023086   0.049590  0.857143

[4340 rows x 3 columns]

##Train Test Split

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X = df.drop('selling_price',axis=1)
y = df['selling_price']

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
X_train.shape

(3472, 2)

In [ ]:
X_test.shape

(868, 2)

## Feature-Scalling: Normalisation: MinMax

In [ ]:
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [ ]:
X_train_scaled

array([[0.02479426, 0.89285714],
       [0.06198751, 0.92857143],
       [0.03099313, 0.75      ],
       ...,
       [0.06322728, 0.85714286],
       [0.09918076, 0.75      ],
       [0.09918076, 0.75      ]])

In [ ]:
X_test_scaled

array([[0.09918076, 0.64285714],
       [0.03347268, 0.96428571],
       [0.05172589, 0.57142857],
       ...,
       [0.04958976, 0.67857143],
       [0.0080325 , 0.89285714],
       [0.03719201, 0.96428571]])

In [ ]:
X_train_scaled = pd.DataFrame(X_train_scaled,columns=X_train.columns)
X_test_scaled =  pd.DataFrame(X_test_scaled,columns=X_train.columns)

In [ ]:
X_test_scaled

     km_driven      year
0     0.099181  0.642857
1     0.033473  0.964286
2     0.051726  0.571429
3     0.174807  0.785714
4     0.074385  0.857143
..         ...       ...
863   0.074385  0.535714
864   0.148772  0.821429
865   0.049590  0.678571
866   0.008033  0.892857
867   0.037192  0.964286

[868 rows x 2 columns]